### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by EnrikvO** [ThoreBor/Anki_Leaderboard#200]
**Describe the bug**
For some reason my account seems to be buggy. I can't log in on my other notebook or reset my password. I tried every possible combination.

**Info**
- Anki version Version ⁨2.1.56 Qt6
- Leaderboard version Leaderboard v3.0.2
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: Mac

**Comment by ThoreBor** [comment]
I need some more information. Why can't you reset your password? Do get an error message? If so please copy it, or send a screenshot.

**Comment by EnrikvO** [comment]
It says: Reset Password Error
Can't find username with that email address

My Accountname is Endrake. I tried all the mails I use. Maybe I had a typo, when I registered.

**Comment by ThoreBor** [comment]
Thanks! I just noticed that email addresses were case-sensitive, but I fixed that now. Please check if it works now. Otherwise, I'm sorry, but there isn't really anything I can do because I can't just tell you the email address.

**Comment by EnrikvO** [comment]
It is still not working. Can I send you a private mail somewhere?

**Comment by ThoreBor** [comment]
leaderboard_support@protonmail.com
