### ISSUE TITLE
Can't open the add friends/create column

### ISSUE THREAD

**Issue by Karyotip** [ThoreBor/Anki_Leaderboard#21]
Can't open the add friends/create column. It only shows leaderboard and report a bug under "Leaderboards". Also, it stopped synching my reviews after about 6pm CST

**Comment by ThoreBor** [comment]
Under Leaderboard should also be "Config" if you're using the newest version. You can add friends there. What do you mean by it stopped syncing?

**Comment by Karyotip** [comment]
I will look for it, thank you!
Even though I kept doing reviews, it stopped showing them on the
leaderboards

**Comment by ThoreBor** [comment]
Alright, please make sure you are using the newest version (v1.2)

**Comment by Karyotip** [comment]
I am definitely using the newest version! Updated, enabled/disabled the
add-on bunch of times, turned on/off the the Anki, nothing helped

**Comment by ThoreBor** [comment]
So you don't see your stats on the leaderboard and can't add friends?

**Comment by Karyotip** [comment]
My stats work fine know, guess cause it's a new day. However, I can't add
friends and there is no "config" under the leaderboards. Btw I am using mac
and another friend, who uses mac, has encountered the same problem. Now, I
can't even change/delete my account
[image: Screen Shot 2020-04-03 at 8.17.31 AM.png]

**Comment by Karyotip** [comment]
One thing I can do is to edit information via tools, but I don't know if it
will further mess up things
[image: Screen Shot 2020-04-03 at 8.29.43 AM.png]

**Comment by ThoreBor** [comment]
That sounds weird. Can you send the screenshots again? I can't see them.

**Comment by cjdduarte** [comment]
I think the error occurs on MacOS versions of Anki

**Comment by Karyotip** [comment]
Sorry, just got done with studying. Here are the screenshots
I tried to use after the newest updates today, still does not work.

**Comment by ThoreBor** [comment]
Still can't see the screenshot... But I think I fixed to reviews not syncing problem. Please download the newest version (v.1.3.1) and let me know if this changed anything for you.

**Comment by Karyotip** [comment]
Yeah, updated last night. The same thing, my reviews stop refreshing after
about 6p.m. CST. Also, if I go to tools->add-ons> config for leaderboards,
I can restore defaults. In that case, the very first time I open the
add-on, it gives me an option to create/login and add friends. After that,
disappears.
Last night I updated to 1.3.1. and for a brief period of time , it actually
showed the correct number of reviews, but then once again set me back to
pre 6p.m.
Sorry, don't know how else to send the screenshots then

**Comment by ThoreBor** [comment]
Okay, I can't really tell what the problem is. Please look at this and confirm that this is not what the add-on looks like on your pc.
![2020-04-04 16-33-22](https://user-images.githubusercontent.com/40232329/78453521-8eb8cd00-7692-11ea-9c27-b6768e8306c7.gif)

**Comment by ThoreBor** [comment]
You you send me a list of the add-ons you're using?

**Comment by Karyotip** [comment]
Unfortunately, it does not look like that to me. here's what I have, I
saved the screenshots as pdfs so should work now. Here are the addons. I
don't think addons are the culprit, cause I tried to disable all of them
and still had that problem with leaderboards.
True Retention3
Anki Killstreaks
Clickable Tags v11
Customize Keyboard Shortcuts
Hierarchical Tags 2  Anki 2117 support
Hitmarkers
Leaderboard
Pop-up Dictionary beta
Progress Bar
ReMemorize Rescheduler with sibling and logging v132
Review Heatmap
Special Fields

**Comment by ThoreBor** [comment]
Did you restart Anki after disabling them? And I still can't see the screenshots. You just have to drag and drop them into the comment field.

**Comment by ThoreBor** [comment]
I think I might've found the review-bug. Some of the epoch milliseconds were converted to gmt instead of local time. I can probably release the new version tomorrow, then you can check if this fixed your problem.

**Comment by Karyotip** [comment]
Ok, I will do that!
And thanks dude! Appreciate all the work
